usuario:
    resource: "@UsuarioBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/usuario
    requirements:
        _locale: en|es

tienda:
    resource: "@TiendaBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/
    requirements:
        _locale: en|es

ciudad:
    resource: "@CiudadBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/
    requirements:
        _locale: en|es

oferta:
    resource: "@OfertaBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/
    requirements:
        _locale: en|es
        
extranet:
    resource: "@TiendaBundle/Resources/config/extranet/routing.yml"
    prefix:   /extranet

pagina_estatica:
    pattern: /{_locale}/sitio/{pagina}
    defaults: { _controller: OfertaBundle:Sitio:estatica }
    requirements:
        _locale: en|es

_portada:
    pattern:  /
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: portada, ciudad: '%cupon.ciudad_por_defecto%' }

portada:
    pattern: /{_locale}/{ciudad}
    defaults: { _controller: OfertaBundle:Default:portada, _locale: es }
    requirements:
        _locale: en|es

# Internal routing configuration to handle ESI
# ****** WARNING ******
# This route should be enabled with caution as it can open a security vulnerability
# see http://symfony.com/blog/security-release-symfony-2-0-20-and-2-1-5-released for more information
# ****** WARNING ******
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
