security:
    firewalls:
        frontend:
            pattern:    ^/*
            anonymous:  ~
            form_login:
                login_path: usuario_login
                check_path: usuario_login_check
                default_target_path: usuario_compras
                always_use_default_target_path: true
            logout:
                path: usuario_logout
            remember_me:
                key:      cupon1234
                lifetime: 3600
            switch_user: { role: ROLE_USUARIO }

    access_control:
        - { path: ^/usuario/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/usuario/registro, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/usuario/*, roles: ROLE_USUARIO }

    providers:
        usuarios:
            entity: { class: Cupon\UsuarioBundle\Entity\Usuario, property: email }
    
    encoders:
        Cupon\UsuarioBundle\Entity\Usuario: { algorithm: sha512, iterations: 10 }
        Cupon\TiendaBundle\Entity\Tienda:  { algorithm: sha512, iterations: 10 }